name: saltproc-env
channels:
  - conda-forge
  - defaults
dependencies:
  - pyne>=0.5.11=nomoab_noopenmc*
  - numpy>=1.14.0
  - pytables
  - networkx
  - pydotplus
  - pytest
  - jsonschema
  - pip:
    - argparse==1.4.0
