name: saltproc-env
channels:
  - conda-forge
  - defaults
dependencies:
  - python < 3.12
  - numpy
  - pytables
  - networkx
  - pydot
  - pytest
  - jsonschema
  - pip:
    - git+https://github.com/CORE-GATECH-GROUP/serpent-tools.git
    - argparse==1.4.0
