name: saltproc-doc-env
channels:
  - conda-forge
  - defaults
dependencies:
  - pyne>=0.5.11=nomoab_noopenmc*
  - openmc
  - numpy>=1.14.0
  - pytables
  - networkx
  - pydotplus
  - sphinx
  - sphinx_rtd_theme
  - jsonschema
  - pip:
      - sphinx-multiversion
      - sphinxcontrib-apidoc
      - sphinx-jsonschema
