#!/bin/bash
#PBS -l nodes=32:ppn=32:xe
#PBS -l walltime=48:00:00
#PBS -N no_removals
#PBS -j oe
#PBS -q normal

### cd to the location where you submitted the job, if needed
### note that you are on a PBS MOM node and not running interactively on a
### compute node

cd $PBS_O_WORKDIR

# To add certain modules that you do not have added via ~/.modules
module swap PrgEnv-cray PrgEnv-gnu
module load cray-hdf5/1.10.0
module load bwpy

python run_saltproc.py
